if(window.top!==window.self){document.documentElement.innerHTML='<body>Acesso incorporado bloqueado.</body>';try{window.top.location=window.self.location}catch(_){} }
const classData=[];
const recoveryData=[];
let schoolName='';
const STORAGE_KEY='mapa-norte-session-v2';const MAX_STORAGE_AGE_MS=12*60*60*1000;const NO_EXAM='Não realizou';
// Aluno que não fez a prova está resolvido, não pendente: não há nota nem bimestre a substituir.
function rowStatus(row){return (row[5]===NO_EXAM||(row[5]!=='—'&&row[6]))?'Concluído':'Pendente'}
// Demais linhas do mesmo aluno na mesma turma. O aluno é identificado por nome + turma,
// a mesma chave usada na mesclagem de lotes.
function sameStudentRows(index){const base=recoveryData[index];return recoveryData.filter((r,i)=>i!==index&&normal(r[0])===normal(base[0])&&normal(r[1])===normal(base[1]))}
function confirmDialog(message){return new Promise(resolve=>{const modal=$('#confirm-modal');$('#confirm-text').textContent=message;modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#confirm-ok').focus();const close=answer=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');$('#confirm-ok').onclick=null;$('#confirm-cancel').onclick=null;document.removeEventListener('keydown',onKey);resolve(answer)};const onKey=event=>{if(event.key==='Escape')close(false)};document.addEventListener('keydown',onKey);$('#confirm-ok').onclick=()=>close(true);$('#confirm-cancel').onclick=()=>close(false)})}
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function clearTemplateAtaSample(){const table=$('.paper-table');if(!table)return;while(table.children.length>6)table.lastElementChild.remove()}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function recoveryScoreOptions(selected){const current=String(selected??'').replace(',','.');return '<option value="">Selecionar</option>'+Array.from({length:10},(_,index)=>String(index+1)).map(value=>`<option value="${value}" ${current===value?'selected':''}>${value}</option>`).join('')+`<option value="${NO_EXAM}" ${current===NO_EXAM?'selected':''}>${NO_EXAM} a prova</option>`}
const MAX_UPLOAD_BYTES=15*1024*1024;const MAX_UPLOAD_FILES=50;const MAX_IMPORTED_RECORDS=2000;
// Endereço da implantação do Apps Script que guarda as salas. Vazio desliga a
// sala inteira e o app volta a funcionar só dentro do navegador, como antes —
// é o estado publicado enquanto a escola não implantar a sua própria cópia.
// Fica aqui em cima, e não junto das funções de sala, porque iniciarSala() roda
// na linha de partida do app: const declarado depois estaria na zona morta.
const SALA_ENDPOINT='https://script.google.com/macros/s/AKfycbzIJHwQvnFb6arEA27GYuj6EU35RpWLa2qnJ_C8XeEWo_Rl1NUg1akBX42Kb13sG7Dc/exec';
const SALA_INTERVALO_MS=8000;
let salaId='',salaVersao=0,salaAvisouErro=false;
// Turma da ATA em exibição. O .minute-row.selected do HTML marca sempre a
// primeira da lista e não acompanha o clique, então não serve para saber isto.
let ataAtual='';
function validateUploadSelection(files){if(files.length>MAX_UPLOAD_FILES)throw new Error(`Selecione no máximo ${MAX_UPLOAD_FILES} arquivos por lote.`);if(files.some(file=>file.size>MAX_UPLOAD_BYTES))throw new Error('Cada planilha deve ter no máximo 15 MB.');}
function rebuildClassData(){const groups=[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean);classData.splice(0,classData.length,...groups.map(name=>{const rows=recoveryData.filter(r=>r[1]===name);return{name,bim:'1º + 2º',students:new Set(rows.map(r=>normal(r[0]))).size,recovery:new Set(rows.map(r=>normal(r[0]))).size,status:'review',label:'Conferir'}}))}
function renderOverview(){const uniqueStudents=new Set(recoveryData.map(r=>`${normal(r[0])}|${normal(r[1])}`)).size;const pending=recoveryData.filter(r=>r[7]!=='Concluído').length;const metrics=$$('.metric-value');if(metrics[0])metrics[0].textContent=String(uniqueStudents).padStart(2,'0');if(metrics[1])metrics[1].innerHTML=`${String(classData.length).padStart(2,'0')} <small>/ ${String(classData.length).padStart(2,'0')}</small>`;if(metrics[2])metrics[2].textContent=String(pending).padStart(2,'0');const cards=$$('.metric-card');if(cards[0])cards[0].querySelector('p').textContent=uniqueStudents?`${recoveryData.length} componentes curriculares`:'Importe um lote para começar';if(cards[1])cards[1].querySelector('p').textContent=classData.length?`${classData.length} turma${classData.length===1?'':'s'} carregada${classData.length===1?'':'s'}`:'Nenhum lote carregado';if(cards[2])cards[2].querySelector('p').textContent=pending?`● ${pending} registro${pending===1?'':'s'} para revisar`:'● nada para revisar';const badge=$('.nav-badge');if(badge)badge.textContent=String(pending)}
function refreshSummary(){rebuildClassData();tableRows();renderClasses();renderOverview()}
function persistLocal(){refreshSummary();try{localStorage.setItem(STORAGE_KEY,JSON.stringify({schoolName,recoveryData,ts:Date.now()}))}catch(error){console.warn('Falha ao salvar sessão:',error)}}
function clearSession(){localStorage.removeItem(STORAGE_KEY);schoolName='';$('#school-name').value='';recoveryData.splice(0,recoveryData.length);classData.splice(0,classData.length);$('#class-filter').innerHTML='<option value="all">Todas as turmas</option>';$('#subject-filter').innerHTML='<option value="all">Todas as disciplinas</option>';refreshSummary();recoveryRows();renderMinutes();renderOverview();toast('Dados apagados.')}
function restoreLocal(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!saved||!Array.isArray(saved.recoveryData))return;if(Date.now()-(saved.ts||0)>MAX_STORAGE_AGE_MS){localStorage.removeItem(STORAGE_KEY);return}schoolName=String(saved.schoolName||'').trim();recoveryData.splice(0,recoveryData.length,...saved.recoveryData.filter(row=>Array.isArray(row)&&row.length>=8));if($('#school-name'))$('#school-name').value=schoolName;refreshSummary();const groups=[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean);const subjects=[...new Set(recoveryData.map(r=>r[2]))].filter(Boolean).sort();$('#class-filter').innerHTML='<option value="all">Todas as turmas</option>'+groups.map(name=>`<option>${escapeHtml(name)}</option>`).join('');$('#subject-filter').innerHTML='<option value="all">Todas as matérias</option>'+subjects.map(name=>`<option>${escapeHtml(name)}</option>`).join('')}catch(error){localStorage.removeItem(STORAGE_KEY);console.warn('Sessão inválida descartada:',error)}}
function tableRows(){ $('#classes-table').innerHTML=classData.map(c=>`<tr><td><div class="class-cell"><span class="class-symbol">${escapeHtml(c.name.match(/^\d+/)?.[0]||'—')}</span><strong>${escapeHtml(c.name)}</strong></div></td><td>${escapeHtml(c.bim)}</td><td>${escapeHtml(c.students)}</td><td>${escapeHtml(c.recovery)} alunos</td><td><span class="status ${c.status}">${escapeHtml(c.label)}</span></td><td class="arrow-cell">→</td></tr>`).join(''); }
function recoveryRows(filter=''){const q=filter.toLowerCase();const selectedClass=$('#class-filter')?.value||'all';const selectedSubject=$('#subject-filter')?.value||'all';const rows=recoveryData.map((r,index)=>({r,index})).filter(x=>x.r.join(' ').toLowerCase().includes(q)&& (selectedClass==='all'||x.r[1]===selectedClass) && (selectedSubject==='all'||x.r[2]===selectedSubject));$('#recovery-table').innerHTML=rows.map(({r,index})=>`<tr><td><strong>${escapeHtml(r[0])}</strong></td><td>${escapeHtml(r[1])}</td><td>${escapeHtml(r[2])}</td><td class="${r[3]!=='—'?'low-score':'empty-score'}">${escapeHtml(r[3])}</td><td class="${r[4]!=='—'?'low-score':'empty-score'}">${escapeHtml(r[4])}</td><td><select class="score-input" data-index="${index}" data-slot="5" aria-label="Nota de recuperação semestral para ${escapeHtml(r[0])} — ${escapeHtml(r[2])}">${recoveryScoreOptions(r[5]==='—'?'':r[5])}</select></td><td><select class="replacement-select" data-index="${index}" ${r[5]===NO_EXAM?'disabled':''} aria-label="Bimestre substituído para ${escapeHtml(r[0])} — ${escapeHtml(r[2])}"><option value="">Selecionar</option><option value="1º bimestre" ${r[6]==='1º bimestre'?'selected':''}>1º bimestre</option><option value="2º bimestre" ${r[6]==='2º bimestre'?'selected':''}>2º bimestre</option></select></td><td><span class="status ${r[7]==='Concluído'?'ready':'review'}">${escapeHtml(r[7])}</span></td></tr>`).join('');$('.toolbar-count').textContent=`${rows.length} registros`;$$('.score-input').forEach(input=>input.addEventListener('change',async e=>{const index=Number(e.target.dataset.index);const row=recoveryData[index];const value=e.target.value.trim();row[5]=value?value.replace('.',','):'—';if(row[5]===NO_EXAM)row[6]='';row[7]=rowStatus(row);if(row[5]===NO_EXAM){const others=sameStudentRows(index);if(others.length){const filled=others.filter(r=>r[5]!=='—').length;const warning=filled?` ${filled} já tem nota lançada e será substituída.`:'';if(await confirmDialog(`${row[0]} tem mais ${others.length} disciplina(s) nesta lista.${warning}`)){others.forEach(r=>{r[5]=NO_EXAM;r[6]='';r[7]=rowStatus(r)});toast(`${others.length+1} registros marcados como ${NO_EXAM}.`)}}}recoveryRows($('#search').value);persistBatch()}));$$('.replacement-select').forEach(select=>select.addEventListener('change',e=>{const row=recoveryData[Number(e.target.dataset.index)];row[6]=e.target.value;row[7]=rowStatus(row);recoveryRows($('#search').value)}));}
function renderClasses(){$('#class-cards').innerHTML=classData.map(c=>`<article class="class-card"><span class="class-symbol">${escapeHtml(c.name.match(/^\d+/)?.[0]||'—')}</span><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.bim)} bimestre • ${escapeHtml(c.students)} alunos</p><div class="progress"><span style="width:${c.status==='wait'?38:Math.max(0,100-c.recovery*8)}%"></span></div><div class="class-card-footer"><span>${escapeHtml(c.recovery)} em recuperação</span><span>${escapeHtml(c.label)}</span></div></article>`).join('');}
function ataRows(className){return recoveryData.filter(r=>r[1]===className).map(r=>`<span>${escapeHtml(r[0])}</span><span>${escapeHtml(r[2])}</span><span>${escapeHtml(r[3])}</span><span>${escapeHtml(r[4])}</span><span>${escapeHtml(r[5]==='—'?'____':r[5])}</span><span>${escapeHtml(r[6]||'____')}</span>`).join('')}
function renderAta(className){const rows=recoveryData.filter(r=>r[1]===className);const paper=$('.paper');if(!paper||!rows.length)return;ataAtual=className;const heading=paper.querySelector('.paper-center');if(heading&&schoolName)heading.innerHTML=`<strong>GOVERNO DO ESTADO DE SÃO PAULO</strong><br />SECRETARIA DE ESTADO DA EDUCAÇÃO<br />UNIDADE REGIONAL DE ENSINO – REGIÃO DE ADAMANTINA<br />E.E. “${escapeHtml(schoolName)}” - SAGRES<br />MUNICÍPIO DE SAGRES`;paper.querySelector('.paper-intro').innerHTML=`Aos ____ dias do mês de agosto de dois mil e vinte e seis, nesta unidade escolar, realizou-se a Avaliação de Recuperação Semestral dos alunos da turma <strong>${escapeHtml(className)}</strong>.`;paper.querySelector('.paper-table').innerHTML='<span>Aluno</span><span>Disciplina</span><span>Nota do primeiro bimestre</span><span>Nota do segundo bimestre</span><span>Nota da recuperação semestral</span><span>Bimestre substituído</span>'+ataRows(className);toast(`ATA de ${className} atualizada.`)}
function renderMinutes(){const groups=[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean);$('#minutes-list').innerHTML=groups.map((name,i)=>{const count=recoveryData.filter(r=>r[1]===name).length;return `<div class="minute-row ${i===0?'selected':''}"><strong>${escapeHtml(name)}</strong><small>${count} registros • Rascunho para revisão</small><button data-ata-class="${escapeHtml(name)}">Revisar ATA →</button></div>`}).join('');$$('[data-ata-class]').forEach(b=>b.onclick=()=>{$$('.minute-row').forEach(linha=>linha.classList.remove('selected'));b.closest('.minute-row')?.classList.add('selected');renderAta(b.dataset.ataClass)});if(groups[0])renderAta(groups[0]);}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}-view`).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:'Visão geral',recovery:'Recuperação',classes:'Turmas',minutes:'Atas'};$('#page-title').textContent=titles[view];window.scrollTo({top:0,behavior:'smooth'});}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function normal(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim().toUpperCase()}
// O cadastro da SEDUC guarda o título honorífico no fim do nome da escola:
// "WALDOMIRO SAMPAIO DE SOUZA PREFEITO". Na ATA ele vai na frente e abreviado.
const SCHOOL_TITLES={PREFEITO:'PREF.',PREFEITA:'PREF.',PROFESSOR:'PROF.',PROFESSORA:'PROFA.',DOUTOR:'DR.',DOUTORA:'DRA.',VEREADOR:'VER.',VEREADORA:'VER.',DEPUTADO:'DEP.',DEPUTADA:'DEP.',GOVERNADOR:'GOV.',SENADOR:'SEN.',SENADORA:'SEN.',CORONEL:'CEL.',CAPITAO:'CAP.',MAJOR:'MAJ.',PADRE:'PE.',MONSENHOR:'MONS.',ENGENHEIRO:'ENG.',DESEMBARGADOR:'DES.',DESEMBARGADORA:'DES.'};
// Caixa alta sem perder acento: nome de escola sai acentuado na ATA. O normal()
// entra só na chave de busca do título, que é comparada sem acento.
function normalizeSchoolName(name){const upper=String(name??'').replace(/\s+/g,' ').trim().toUpperCase();if(!upper)return '';const words=upper.split(' ');if(words.length<2)return upper;const title=SCHOOL_TITLES[normal(words[words.length-1])];return title?`${title} ${words.slice(0,-1).join(' ')}`:upper}
function cleanSubject(v){return String(v??'').replace(/\s*\([12]B\)\s*$/i,'').replace(/\s+\d{3,6}\s*$/,'').trim()}
function cleanClassName(v){return String(v??'').replace(/\.(xlsx|xls)$/i,'').replace(/[_]+/g,' ').replace(/\s+/g,' ').trim()}
// Fundamental usa ANO, ensino médio usa SÉRIE, e o ordinal vem º, ° ou ª.
// No Mapão consolidado a turma só existe no nome do arquivo.
const TURMA_RE=/\d+\s*[ºª°]?\s*(?:ANO|S[ÉE]RIE)\b/i;
const TURMA_NOME_RE=/\d+\s*[ºª°]?\s*(?:ANO|S[ÉE]RIE)[^_\-]*/i;
const TRANSFER_RE=/(BAIXA\s+DE\s+TRANSFER|TRANSFERID[OA]|TRANSFER[ÊE]NCIA|MATR[IÍ]CULA\s+BAIXADA)/i;
// A situação é da linha, não do aluno. No Mapão consolidado um mesmo aluno pode ter
// uma linha de baixa da matrícula antiga e outra ativa da atual. Excluir pelo nome
// apagava também a linha ativa e o aluno sumia da recuperação inteiro. Só sai da
// lista quem não tem nenhuma linha ativa na planilha.
function droppedStudents(rows){const transferred=new Set(),active=new Set();rows.forEach(row=>{const nome=normal(row[0]);if(!nome)return;(TRANSFER_RE.test(row.join(' '))?transferred:active).add(nome)});return new Set([...transferred].filter(nome=>!active.has(nome)))}
// FAQ da Recuperação Semestral 2026, item 6.1: Arte, Educação Física, Projeto de
// Vida e Redação e Leitura não participam da recuperação semestral, porque não
// integram a Prova Paulista. Nota baixa nesses componentes não gera prova, então
// eles não entram na lista nem na ATA.
// Outros componentes de itinerário e de apoio — Orientação de Estudo, Práticas
// Experimentais, Robótica, Eletivas e afins — também não estão na Prova Paulista,
// mas o FAQ não os nomeia. Ficam na lista até a Diretoria de Ensino confirmar.
const SEM_PROVA_RECUPERACAO=new Set(['ARTE','ARTES','EDUCACAO FISICA','PROJETO DE VIDA','REDACAO E LEITURA']);
function temProvaDeRecuperacao(disciplina){return !SEM_PROVA_RECUPERACAO.has(normal(disciplina))}
function subjectPeriod(v,fallback){const match=normal(v).match(/\(([12])B\)/);return match?`${match[1]}º`:fallback}
function findTurma(rows,fileName){for(const row of rows){for(let i=0;i<row.length;i++){if(normal(row[i])==='TURMA:'||normal(row[i])==='TURMA'){const value=row.slice(i+1).find(v=>String(v??'').trim());if(value)return cleanClassName(value)}}}const fallback=rows.flat().map(v=>String(v??'').trim()).find(v=>TURMA_RE.test(v));if(fallback)return cleanClassName(fallback);const fromName=String(fileName).replace(/\.(xlsx|xls)$/i,'').match(TURMA_NOME_RE);return fromName?cleanClassName(fromName[0]):'Turma não identificada'}
function bimester(name,metadata=[]){const file=normal(name).replace(/[_-]+/g,' ');const meta=normal(metadata.flat().join(' '));const second=value=>value.includes('SEGUNDO BIMESTRE')||/(^|\D)2\s*[º°O]?\s*BIM/.test(value);const first=value=>value.includes('PRIMEIRO BIMESTRE')||/(^|\D)1\s*[º°O]?\s*BIM/.test(value);if(second(file))return'2º';if(first(file))return'1º';if(second(meta))return'2º';return'1º'}
function parseNumber(v){const raw=typeof v==='number'?v:String(v??'').replace(',','.').replace(/[^0-9.-]/g,'');if(raw==='')return null;const value=Number(raw);return Number.isFinite(value)&&value>=0&&value<=10?value:null}
// A costura entre a planilha e a lógica é o array de linhas que o SheetJS entrega.
// Tudo abaixo de readSheetRows é função pura sobre esse array, o que deixa o
// parser inteiro testável em Node, sem XLSX e sem DOM. Ver test-parser.mjs.
function readSheetRows(buffer){if(!window.XLSX)throw new Error('Biblioteca Excel indisponível');const book=XLSX.read(buffer,{type:'array',cellDates:false});return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:''})}
// parseSheet cabe em uma linha de propósito: o test-parser.mjs extrai estas
// declarações do arquivo por linha, para não manter uma segunda cópia das regras.
// O Mapão por bimestre fecha com um bloco de legenda ("ES - Engajamento
// Satisfatório" e afins), que são linhas de texto na coluna do aluno. A leitura
// para ali; sem isso, uma legenda com número ao lado viraria aluno fantasma.
function parseSheet(rows,fileName){const headerIndex=rows.findIndex(row=>row.some(v=>normal(v)==='ALUNO'));if(headerIndex<0)throw new Error(`ALUNO não encontrado em ${fileName}`);const header=rows[headerIndex];const second=rows[headerIndex+1]||[];const rawLabels=header.map((v,i)=>String(v||second[i]||''));const labels=rawLabels.map(v=>normal(v));const stop=labels.findIndex((v,i)=>i>1&&['TOTAL','TF','FRE(%)','FT AN','FRE AN(%)'].includes(v));const last=stop>0?stop:labels.length;const metadata=rows.slice(0,headerIndex);const turma=findTurma(metadata,fileName);const period=bimester(fileName,metadata);const records=[];for(const row of rows.slice(headerIndex+1)){const aluno=String(row[0]??'').trim();if(normal(aluno)==='LEGENDA')break;if(!aluno||normal(aluno)==='ALUNO'||aluno.length<4)continue;for(let i=2;i<last;i++){const rawSubject=rawLabels[i];const subject=cleanSubject(rawSubject);if(['M','F','AC'].includes(normal(subject)))continue;const score=parseNumber(row[i]);if(subject&&score!==null&&score<5)records.push({aluno,turma,disciplina:subject,bimestre:subjectPeriod(rawSubject,period),nota:score});}}return {file:fileName,bimestre:period,turma,records}}
// Nome da escola nas linhas de metadado acima do cabeçalho. O Mapão consolidado
// não tem essas linhas, então devolve vazio e o campo da tela fica para digitar.
const SCHOOL_LABELS=['ESCOLA','NOME DA ESCOLA','UNIDADE ESCOLAR','UNIDADE DE ENSINO','NOME DA UNIDADE'];
function detectSchool(rows){const metadata=rows.slice(0,Math.max(1,rows.findIndex(row=>row.some(value=>normal(value)==='ALUNO'))));let escola='';for(const row of metadata){for(let i=0;i<row.length;i++){const label=normal(row[i]).replace(/:$/,'');if(SCHOOL_LABELS.includes(label)){const value=row.slice(i+1).find(item=>String(item??'').trim());if(value)escola=String(value).trim()}}}if(!escola)escola=metadata.flat().map(value=>String(value??'').trim()).find(value=>/^E\.?E\.?\s*[“"]?/i.test(value))||'';return normalizeSchoolName(escola.replace(/^E\.?E\.?\s*[“"]?/i,'').replace(/[”"]$/,''))}
// Um registro só entra na recuperação se o aluno continua matriculado, se o
// componente tem prova, e se o texto do próprio registro não é uma marca de saída.
function keepRecords(records,rows){const dropped=droppedStudents(rows);return records.filter(record=>!dropped.has(normal(record.aluno))&&temProvaDeRecuperacao(record.disciplina)&&!TRANSFER_RE.test(`${record.aluno} ${record.turma} ${record.disciplina}`))}
// A planilha que o app exporta pode voltar preenchida: duas pessoas dividem o
// lançamento numa planilha compartilhada do Drive e devolvem o arquivo. Ela já
// vem combinada, uma linha por aluno + turma + disciplina, então não passa pelo
// parser do Mapão — seria lido como se cada coluna de nota fosse uma matéria.
// Nada do arquivo é aceito como veio: nota, bimestre e status são revalidados.
function notaBimestre(v){const nota=parseNumber(v);return nota===null?'—':String(nota).replace('.',',')}
function notaRecuperacao(v){const texto=String(v??'').trim();if(normal(texto)===normal(NO_EXAM))return NO_EXAM;const nota=parseNumber(texto);return nota!==null&&Number.isInteger(nota)&&nota>=1?String(nota):'—'}
function bimestreSubstituido(v){const texto=String(v??'').trim();return /^[12]/.test(texto)?`${texto[0]}º bimestre`:''}
// Toda linha que chega de fora — planilha devolvida ou sala compartilhada —
// passa por aqui. Nenhum dos dois é fonte confiável: um foi editado à mão no
// Sheets, o outro chega pela rede de uma implantação aberta.
function linhaValidada(aluno,turma,disciplina,nota1,nota2,recuperacaoBruta,bimestreBruto){const recuperacao=notaRecuperacao(recuperacaoBruta);const linha=[String(aluno??'').trim(),cleanClassName(turma),cleanSubject(disciplina),notaBimestre(nota1),notaBimestre(nota2),recuperacao,recuperacao===NO_EXAM?'':bimestreSubstituido(bimestreBruto),''];linha[7]=rowStatus(linha);return linha}
function parseExport(rows){const head=rows.findIndex(row=>normal(row[0])==='ALUNO'&&normal(row[1])==='TURMA'&&normal(row[2])==='DISCIPLINA');if(head<0)return null;return rows.slice(head+1).filter(row=>String(row[0]??'').trim()).map(row=>linhaValidada(row[0],row[1],row[2],row[3],row[4],row[5],row[6]))}
async function extractWorkbook(file){const rows=readSheetRows(await file.arrayBuffer());const restored=parseExport(rows);if(restored)return{file:file.name,restored,records:[],escola:''};const parsed=parseSheet(rows,file.name);parsed.records=keepRecords(parsed.records,rows);parsed.escola=detectSchool(rows);return parsed}
// Sala compartilhada: duas pessoas abrem o mesmo link e digitam nota ao mesmo
// tempo. O código da sala é o único segredo, porque a implantação do Apps
// Script é aberta — sem I, O, 0 e 1 para ninguém errar ao ditar por telefone.
const SALA_ALFABETO='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function novaSala(sorteio=n=>crypto.getRandomValues(new Uint8Array(n))){return [...sorteio(12)].map(byte=>SALA_ALFABETO[byte%SALA_ALFABETO.length]).join('')}
// A chave é montada aqui e viaja pronta: o Apps Script só compara string, e
// assim a regra de identidade do aluno continua existindo num lugar só.
function chaveDaLinha(row){return `${normal(row[0])}|${normal(row[1])}|${normal(row[2])}`}
function linhasParaSala(rows){return rows.map(row=>[chaveDaLinha(row),...row.slice(0,7)])}
function linhasDaSala(linhas){return (Array.isArray(linhas)?linhas:[]).filter(linha=>Array.isArray(linha)&&String(linha[1]??'').trim()).map(linha=>linhaValidada(linha[1],linha[2],linha[3],linha[4],linha[5],linha[6],linha[7]))}
function salaDaUrl(hash){const match=String(hash||'').match(/sala=([A-Za-z0-9]{8,32})/);return match?match[1].toUpperCase():''}
// Junta os registros soltos em uma linha por aluno + turma + disciplina, com as
// notas dos dois bimestres lado a lado. O bimestre substituído já vem sugerido
// como o de menor desempenho, conforme o item 7.3 do FAQ da recuperação.
function combineRecords(records){const combined=new Map();for(const r of records){const turma=cleanClassName(r.turma);const key=`${r.aluno}|${turma}|${r.disciplina}`;const current=combined.get(key)||{aluno:r.aluno,turma,disciplina:r.disciplina,first:'—',second:'—'};if(r.bimestre==='1º')current.first=String(r.nota).replace('.',',');if(r.bimestre==='2º')current.second=String(r.nota).replace('.',',');combined.set(key,current)}return [...combined.values()].map(r=>{const first=parseNumber(r.first),second=parseNumber(r.second);const replacement=r.first==='—'?'2º bimestre':r.second==='—'?'1º bimestre':first<=second?'1º bimestre':'2º bimestre';return [r.aluno,r.turma,r.disciplina,r.first,r.second,'—',replacement,'Pendente']})}
// Mescla o lote novo com o que já estava na tela. Nota lançada à mão sobrevive:
// só é sobrescrita quando o lote novo traz valor para aquele mesmo campo.
function mergeRows(previous,incoming){const merged=new Map(previous.map(row=>[`${normal(row[0])}|${normal(row[1])}|${normal(row[2])}`,row.slice()]));for(const row of incoming){const key=`${normal(row[0])}|${normal(row[1])}|${normal(row[2])}`;const old=merged.get(key);if(!old){merged.set(key,row.slice());continue}old[3]=row[3]!=='—'?row[3]:old[3];old[4]=row[4]!=='—'?row[4]:old[4];if(row[5]!=='—')old[5]=row[5];if(row[6])old[6]=row[6];old[7]=rowStatus(old)}return [...merged.values()]}
function showImported(parsed,restored=[]){const imported=parsed.flatMap(x=>x.records);if(!imported.length&&!restored.length){toast('Arquivos lidos, mas nenhuma nota abaixo de 5,0 foi encontrada.');return}recoveryData.splice(0,recoveryData.length,...mergeRows(combineRecords(imported),restored));const groups=[...new Set(recoveryData.map(r=>r[1]))];const subjects=[...new Set(recoveryData.map(r=>r[2]))].sort();classData.splice(0,classData.length,...groups.map(name=>({name,bim:'1º + 2º',students:new Set(recoveryData.filter(r=>r[1]===name).map(r=>r[0])).size,recovery:recoveryData.filter(r=>r[1]===name).length,status:'review',label:'Conferir'})));$('#class-filter').innerHTML='<option value="all">Todas as turmas</option>'+groups.map(name=>`<option>${escapeHtml(name)}</option>`).join('');$('#subject-filter').innerHTML='<option value="all">Todas as matérias</option>'+subjects.map(name=>`<option>${escapeHtml(name)}</option>`).join('');tableRows();renderClasses();recoveryRows();persistLocal();$('#upload-modal').classList.remove('open');toast(`${parsed.length} arquivos processados. ${recoveryData.length} pendências encontradas.`)}
// A ATA em .docx vem de uma biblioteca de 1,1 MB, carregada só quando alguém
// clica no botão. Rede de escola é lenta, quem só imprime não paga esse peso, e
// CDN bloqueado derruba apenas este botão — o resto do app segue inteiro.
const DOCX_URL='https://cdn.jsdelivr.net/npm/docx@9.7.1/dist/index.iife.js';
const DOCX_SRI='sha384-9OH56uLhIvkZkwF0jWNlfpcK3gPuSy5DfEMNqKe156wCpkND+MDdtaRyd05kwpG0';
const ATA_COLUNAS=['Aluno','Disciplina','Nota do primeiro bimestre','Nota do segundo bimestre','Nota da recuperação semestral','Bimestre substituído'];
let docxCarregando=null;
// Mesmas células que a ATA da tela mostra, incluindo o ____ de campo em branco.
function celulasDaAta(rows){return [ATA_COLUNAS,...rows.map(row=>[row[0],row[2],row[3],row[4],row[5]==='—'?'____':row[5],row[6]||'____'])]}
function nomeDoArquivoAta(className){return `ata-${String(className||'turma').normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^A-Za-z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()}.docx`}
function carregarDocx(){if(window.docx)return Promise.resolve(window.docx);if(docxCarregando)return docxCarregando;docxCarregando=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=DOCX_URL;script.integrity=DOCX_SRI;script.crossOrigin='anonymous';script.onload=()=>window.docx?resolve(window.docx):reject(new Error('a biblioteca do Word não se anunciou'));script.onerror=()=>{docxCarregando=null;reject(new Error('não foi possível baixar a biblioteca do Word'))};document.head.appendChild(script)});return docxCarregando}
// Sem brasão a ATA continua válida, então falha de imagem não interrompe nada.
async function brasaoParaWord(){try{const resposta=await fetch('brasao-sp.png');return resposta.ok?await resposta.arrayBuffer():null}catch(erro){return null}}
function montarAtaWord(lib,className,rows,brasao){const{Document,Paragraph,TextRun,Table,TableRow,TableCell,ImageRun,AlignmentType,WidthType,BorderStyle}=lib;const nada={style:BorderStyle.NONE,size:0,color:'FFFFFF'};const invisivel={top:nada,bottom:nada,left:nada,right:nada};const cabecalho=['GOVERNO DO ESTADO DE SÃO PAULO','SECRETARIA DE ESTADO DA EDUCAÇÃO','UNIDADE REGIONAL DE ENSINO – REGIÃO DE ADAMANTINA',`E.E. “${schoolName||'PREF. WALDOMIRO SAMPAIO DE SOUZA'}” - SAGRES`,'MUNICÍPIO DE SAGRES'].map((linha,i)=>new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:linha,bold:i===0,size:20})]}));const topo=brasao?[new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:invisivel,rows:[new TableRow({children:[new TableCell({width:{size:18,type:WidthType.PERCENTAGE},borders:invisivel,children:[new Paragraph({children:[new ImageRun({type:'png',data:brasao,transformation:{width:60,height:70}})]})]}),new TableCell({borders:invisivel,children:cabecalho})]})]})]:cabecalho;const celulas=celulasDaAta(rows);const tabela=new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:celulas.map((linha,indice)=>new TableRow({children:linha.map(valor=>new TableCell({children:[new Paragraph({children:[new TextRun({text:String(valor),bold:indice===0,size:16})]})]}))}))});return new Document({sections:[{children:[...topo,new Paragraph({text:''}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'ATA DE RECUPERAÇÃO SEMESTRAL — 2026',bold:true,size:24})]}),new Paragraph({text:''}),new Paragraph({children:[new TextRun({text:'Aos ____ dias do mês de agosto de dois mil e vinte e seis, nesta unidade escolar, realizou-se a Avaliação de Recuperação Semestral dos alunos da turma '}),new TextRun({text:String(className),bold:true}),new TextRun({text:'.'})]}),new Paragraph({text:''}),tabela,new Paragraph({text:''}),new Paragraph({text:''}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'____________________          ____________________'})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'Coordenação                              Direção',size:18})]})]}]})}
function baixarBlob(blob,nome){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=nome;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}
async function baixarAtaWord(){const className=ataAtual||[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean)[0];const rows=recoveryData.filter(r=>r[1]===className);if(!rows.length){toast('Importe um lote antes de gerar a ATA.');return}toast('Preparando o Word…');try{const lib=await carregarDocx();const blob=await lib.Packer.toBlob(montarAtaWord(lib,className,rows,await brasaoParaWord()));baixarBlob(blob,nomeDoArquivoAta(className));toast(`ATA de ${className} baixada em Word.`)}catch(erro){console.warn('Falha ao gerar o Word:',erro);toast('Não foi possível gerar o Word. Use Imprimir / PDF.')}}
function exportRecovery(){if(!window.XLSX){toast('Biblioteca Excel indisponível.');return}const rows=[['Aluno','Turma','Disciplina','Nota do primeiro bimestre','Nota do segundo bimestre','Nota da recuperação semestral','Bimestre substituído','Status'],...recoveryData];const book=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet(rows);XLSX.utils.book_append_sheet(book,sheet,'Recuperação');XLSX.writeFile(book,'lista-recuperacao-2026.xlsx');toast('Excel exportado com sucesso.')}
function printAta(){const paper=$('.paper');if(!paper)return;const printWindow=window.open('','_blank','width=900,height=700');if(!printWindow){toast('Navegador bloqueou janela de impressão.');return}printWindow.document.write(`<html lang="pt-BR"><head><title>ATA de recuperação — 2026</title><base href="${escapeHtml(location.href)}" /><style>body{font-family:Times New Roman,serif;color:#24352c;padding:40px;line-height:1.5}.paper-head{display:flex;align-items:center;gap:16px}.brasao{flex:none;width:70px;height:auto}.paper-head .paper-center{flex:1;margin:0}.paper-center{text-align:center;font-size:12px}.paper h4{text-align:center;margin:25px 0}.paper-table{display:grid;grid-template-columns:2fr 1.4fr 1fr 1fr 1fr 1fr;border-top:1px solid #999;border-bottom:1px solid #999}.paper-table span{padding:6px;border-bottom:1px solid #ddd;font-size:10px}.signatures{display:flex;justify-content:space-around;text-align:center;margin-top:80px}.signatures small{display:block}</style></head><body><div class="paper">${paper.innerHTML}</div><script>window.onload=()=>window.print()<\/script></body></html>`);printWindow.document.close()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#clear-session').onclick=clearSession;$('#open-upload').onclick=()=>$('#upload-modal').classList.add('open');$('#open-upload-2').onclick=()=>$('#upload-modal').classList.add('open');$('#close-upload').onclick=()=>$('#upload-modal').classList.remove('open');$('#search').oninput=e=>recoveryRows(e.target.value);$('#class-filter').onchange=()=>recoveryRows($('#search').value);$('#subject-filter').onchange=()=>recoveryRows($('#search').value);$('#export-recovery').onclick=exportRecovery;$('#generate-minutes').onclick=()=>{renderMinutes();toast('ATAs geradas para revisão.')};$('#print-ata').onclick=printAta;$('#download-ata-word').onclick=baixarAtaWord;$$('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));
clearTemplateAtaSample();restoreLocal();tableRows();recoveryRows();renderClasses();renderMinutes();renderOverview();iniciarSala();

function canonicalizeImportedRecords(parsed){const maps={aluno:new Map(),turma:new Map(),disciplina:new Map()};for(const file of parsed){for(const record of file.records||[]){for(const field of Object.keys(maps)){const key=normal(record[field]);if(maps[field].has(key))record[field]=maps[field].get(key);else maps[field].set(key,record[field])}}}return parsed}
// Ponto de entrada do lote. Antes existiam três camadas empilhadas por
// reatribuição de showImported, e a ordem delas não estava escrita em lugar
// nenhum. Agora a sequência é esta função, de cima para baixo.
function importBatch(parsed){const restored=parsed.flatMap(file=>file.restored||[]);const importedCount=parsed.reduce((total,file)=>total+(file.records||[]).length,0)+restored.length;if(importedCount>MAX_IMPORTED_RECORDS){toast(`Lote excede o limite de ${MAX_IMPORTED_RECORDS} registros.`);return}const escola=parsed.map(file=>file.escola).find(Boolean);if(escola){schoolName=escola;$('#school-name').value=schoolName;toast(`Escola identificada no Mapão: ${schoolName}`)}const previous=recoveryData.map(row=>row.slice());showImported(canonicalizeImportedRecords(parsed),restored);if(previous.length)recoveryData.splice(0,recoveryData.length,...mergeRows(previous,recoveryData));refreshSummary();recoveryRows();renderMinutes();persistLocal();if(SALA_ENDPOINT)(salaId?salvarSala():criarSala()).catch(salaErro);toast(restored.length?`${recoveryData.length} registros acumulados, ${restored.length} de planilha preenchida.`:`${recoveryData.length} registros acumulados.`)}
function salaLigada(){return Boolean(SALA_ENDPOINT&&salaId)}
async function salaGet(params){const resposta=await fetch(`${SALA_ENDPOINT}?${new URLSearchParams(params)}`);if(!resposta.ok)throw new Error(`Sala respondeu ${resposta.status}`);return resposta.json()}
// text/plain de propósito: com application/json o navegador manda um preflight
// OPTIONS, que o Apps Script não responde. Assim a requisição é simples e passa.
async function salaPost(corpo){const resposta=await fetch(SALA_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(corpo)});if(!resposta.ok)throw new Error(`Sala respondeu ${resposta.status}`);return resposta.json()}
// Sala fora do ar não pode derrubar o trabalho: o lote segue no localStorage e
// a pessoa continua digitando. O aviso sai uma vez, não a cada 8 segundos.
function salaErro(error){console.warn('Sala indisponível:',error);if(salaAvisouErro)return;salaAvisouErro=true;toast('Sala fora do ar. Você continua trabalhando, mas o que digitar agora fica só neste aparelho.')}
function aplicarLinhas(linhas){recoveryData.splice(0,recoveryData.length,...linhas);persistLocal();recoveryRows($('#search')?.value||'');renderMinutes()}
// Salvar o lote inteiro busca antes o que está no servidor e mescla com o
// servidor por base: assim nota digitada pela outra pessoa não é atropelada por
// uma importação, e a alteração local ainda vence onde ela existe.
async function salvarSala(){if(!salaLigada())return;const atual=await salaGet({sala:salaId});const remoto=linhasDaSala(atual.linhas);if(remoto.length)recoveryData.splice(0,recoveryData.length,...mergeRows(remoto,recoveryData));const dados=await salaPost({acao:'salvar',sala:salaId,escola:schoolName,linhas:linhasParaSala(recoveryData)});salaVersao=Number(dados.versao)||salaVersao;salaAvisouErro=false;aplicarLinhas(recoveryData.slice())}
async function lancarNaSala(row){if(!salaLigada())return;const dados=await salaPost({acao:'lancar',sala:salaId,chave:chaveDaLinha(row),recuperacao:row[5],bimestre:row[6]});salaVersao=Number(dados.versao)||salaVersao;salaAvisouErro=false}
async function baixarSala(){const dados=await salaGet({sala:salaId});salaVersao=Number(dados.versao)||0;if(dados.escola&&!schoolName){schoolName=String(dados.escola).slice(0,200);$('#school-name').value=schoolName}const linhas=linhasDaSala(dados.linhas);if(linhas.length)aplicarLinhas(linhas);salaAvisouErro=false}
function mostrarSala(){const barra=$('#sala-bar');if(!barra)return;barra.hidden=!salaLigada();if(salaLigada())$('#sala-link').value=`${location.origin}${location.pathname}#sala=${salaId}`}
async function abrirSala(codigo){salaId=codigo;mostrarSala();await baixarSala()}
async function criarSala(){salaId=novaSala();location.hash=`sala=${salaId}`;mostrarSala();await salvarSala();toast('Sala criada. Copie o link e mande para quem vai ajudar.')}
// Quem chega pelo link entra na sala existente. Quem não tem sala nenhuma só
// passa a ter uma quando importa um lote, em importBatch.
function iniciarSala(){if(!SALA_ENDPOINT)return;const codigo=salaDaUrl(location.hash);if(codigo)abrirSala(codigo).catch(salaErro);setInterval(()=>conferirSala().catch(salaErro),SALA_INTERVALO_MS)}
// Pergunta só a versão, que é um contador barato, e só baixa o lote quando ela
// muda. Não atualiza a tela enquanto alguém está com um seletor aberto.
async function conferirSala(){if(!salaLigada()||document.hidden)return;if(document.activeElement?.matches?.('select'))return;const dados=await salaGet({sala:salaId,acao:'versao'});if(Number(dados.versao)===salaVersao)return;await baixarSala();toast('Lista atualizada por quem está na sala com você.')}
function persistBatch(row){persistLocal();if(!salaLigada())return;(row?lancarNaSala(row):salvarSala()).catch(salaErro)}
function validateRecoveryScore(event){if(!event.target.matches('.score-input'))return;const raw=event.target.value.trim().replace(',','.');if(raw===''||raw===NO_EXAM){event.target.setCustomValidity('');return}const score=Number(raw);if(Number.isInteger(score)&&score>=1&&score<=10){event.target.setCustomValidity('');return}event.preventDefault();event.stopImmediatePropagation();const row=recoveryData[Number(event.target.dataset.index)];event.target.value=row&&row[5]!=='—'?String(row[5]).replace(',','.'):'';event.target.setCustomValidity('Informe uma nota inteira entre 1 e 10.');event.target.reportValidity();toast('Nota inválida. Informe uma nota inteira entre 1 e 10.')}
document.addEventListener('change',validateRecoveryScore,true);
document.addEventListener('change',event=>{if(event.target.id!=='folder-input')return;try{validateUploadSelection([...event.target.files])}catch(error){event.preventDefault();event.stopImmediatePropagation();event.target.value='';toast(error.message)}},true);
document.addEventListener('change',event=>{if(event.target.id!=='folder-input')return;const fileName=[...event.target.files].map(file=>file.name).find(name=>/E\.?E\.?|ESCOLA|UNIDADE/i.test(name));if(fileName){const detected=fileName.replace(/\.(xlsx|xls)$/i,'').replace(/[_-]+/g,' ').replace(/\b(1|2)\s*[º°]?\s*BIMESTRE.*$/i,'').trim();if(detected.length>=4){schoolName=normalizeSchoolName(detected);$('#school-name').value=schoolName;toast(`Escola identificada: ${schoolName}`)}}},true);
document.addEventListener('change',event=>{if(!event.target.matches('.score-input,.replacement-select'))return;persistBatch(recoveryData[Number(event.target.dataset.index)])});
$('#school-name').addEventListener('input',event=>{schoolName=event.target.value.trim();renderMinutes()});
// Normaliza ao sair do campo, não a cada tecla, para não brigar com quem digita.
// Com o Mapão consolidado a escola não vem na planilha, então digitar é o
// caminho normal — e sem isto o nome vai cru para a ATA, com o título no fim.
$('#sala-copiar')?.addEventListener('click',()=>{const campo=$('#sala-link');campo.select();const copia=navigator.clipboard?.writeText(campo.value);if(copia&&copia.then)copia.then(()=>toast('Link copiado.')).catch(()=>toast('Selecione e copie o link acima.'));else toast('Selecione e copie o link acima.')});
$('#school-name').addEventListener('change',event=>{const nome=normalizeSchoolName(event.target.value);if(nome===schoolName)return;schoolName=nome;event.target.value=nome;renderMinutes();persistLocal()});
$('#refresh-page').onclick=()=>{persistLocal();location.reload()};
// A data do topo era fixa no HTML e envelhecia sozinha: quem abrisse o link via
// a data de quando a página foi escrita.
function hojePorExtenso(agora=new Date()){const texto=agora.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).replace(/ de /g,' ');return texto.charAt(0).toUpperCase()+texto.slice(1)}
if($('#hoje'))$('#hoje').textContent=hojePorExtenso();
// O SheetJS vem de cdn.sheetjs.com. Rede de escola às vezes bloqueia CDN, e sem
// esta checagem o erro saía como "arquivos ignorados por erro", que culpa a
// planilha de quem está usando em vez da rede.
$('#folder-input').onchange=async e=>{if(!e.target.files.length)return;if(!window.XLSX){toast('Leitor de planilha não carregou. Verifique a conexão e recarregue a página.');e.target.value='';return}toast('Lendo planilhas…');const results=await Promise.allSettled([...e.target.files].map(extractWorkbook));const parsed=results.filter(result=>result.status==='fulfilled').map(result=>result.value);const failed=results.filter(result=>result.status==='rejected');failed.forEach(result=>console.error(result.reason));if(parsed.length)importBatch(parsed);if(failed.length)toast(`${parsed.length} arquivos processados; ${failed.length} ignorados por erro.`)};
