if(window.top!==window.self){document.documentElement.innerHTML='<body>Acesso incorporado bloqueado.</body>';try{window.top.location=window.self.location}catch(_){} }
const classData=[];
const recoveryData=[];
let schoolName='';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function clearTemplateAtaSample(){const table=$('.paper-table');if(!table)return;while(table.children.length>6)table.lastElementChild.remove()}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function recoveryScoreOptions(selected){const current=String(selected??'').replace(',','.');return '<option value="">Selecionar</option>'+Array.from({length:10},(_,index)=>String(index+1)).map(value=>`<option value="${value}" ${current===value?'selected':''}>${value}</option>`).join('')}
const MAX_UPLOAD_BYTES=15*1024*1024;const MAX_UPLOAD_FILES=10;const MAX_IMPORTED_RECORDS=2000;
function validateUploadSelection(files){if(files.length>MAX_UPLOAD_FILES)throw new Error(`Selecione no máximo ${MAX_UPLOAD_FILES} arquivos por lote.`);if(files.some(file=>file.size>MAX_UPLOAD_BYTES))throw new Error('Cada planilha deve ter no máximo 15 MB.');}
function rebuildClassData(){const groups=[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean);classData.splice(0,classData.length,...groups.map(name=>{const rows=recoveryData.filter(r=>r[1]===name);return{name,bim:'1º + 2º',students:new Set(rows.map(r=>normal(r[0]))).size,recovery:new Set(rows.map(r=>normal(r[0]))).size,status:'review',label:'Conferir'}}))}
function renderOverview(){const uniqueStudents=new Set(recoveryData.map(r=>`${normal(r[0])}|${normal(r[1])}`)).size;const pending=recoveryData.filter(r=>r[7]!=='Concluído').length;const metrics=$$('.metric-value');if(metrics[0])metrics[0].textContent=String(uniqueStudents).padStart(2,'0');if(metrics[1])metrics[1].innerHTML=`${String(classData.length).padStart(2,'0')} <small>/ ${String(classData.length).padStart(2,'0')}</small>`;if(metrics[2])metrics[2].textContent=String(pending).padStart(2,'0');const cards=$$('.metric-card');if(cards[0])cards[0].querySelector('p').textContent=uniqueStudents?`${recoveryData.length} componentes curriculares`:'Importe um lote para começar';if(cards[1])cards[1].querySelector('p').textContent=classData.length?`${classData.length} turma${classData.length===1?'':'s'} carregada${classData.length===1?'':'s'}`:'Nenhum lote carregado';if(cards[2])cards[2].querySelector('p').textContent=pending?`● ${pending} registro${pending===1?'':'s'} para revisar`:'● nada para revisar';const badge=$('.nav-badge');if(badge)badge.textContent=String(pending)}
function refreshSummary(){rebuildClassData();tableRows();renderClasses();renderOverview()}
function persistLocal(){refreshSummary()}
function clearSession(){recoveryData.splice(0,recoveryData.length);classData.splice(0,classData.length);$('#class-filter').innerHTML='<option value="all">Todas as turmas</option>';$('#subject-filter').innerHTML='<option value="all">Todas as disciplinas</option>';refreshSummary();recoveryRows();renderMinutes();renderOverview();toast('Sessão limpa.')}
function restoreLocal(){}
function tableRows(){ $('#classes-table').innerHTML=classData.map(c=>`<tr><td><div class="class-cell"><span class="class-symbol">${escapeHtml(c.name.match(/^\d+/)?.[0]||'—')}</span><strong>${escapeHtml(c.name)}</strong></div></td><td>${escapeHtml(c.bim)}</td><td>${escapeHtml(c.students)}</td><td>${escapeHtml(c.recovery)} alunos</td><td><span class="status ${c.status}">${escapeHtml(c.label)}</span></td><td class="arrow-cell">→</td></tr>`).join(''); }
function recoveryRows(filter=''){const q=filter.toLowerCase();const selectedClass=$('#class-filter')?.value||'all';const selectedSubject=$('#subject-filter')?.value||'all';const rows=recoveryData.map((r,index)=>({r,index})).filter(x=>x.r.join(' ').toLowerCase().includes(q)&& (selectedClass==='all'||x.r[1]===selectedClass) && (selectedSubject==='all'||x.r[2]===selectedSubject));$('#recovery-table').innerHTML=rows.map(({r,index})=>`<tr><td><strong>${escapeHtml(r[0])}</strong></td><td>${escapeHtml(r[1])}</td><td>${escapeHtml(r[2])}</td><td class="${r[3]!=='—'?'low-score':'empty-score'}">${escapeHtml(r[3])}</td><td class="${r[4]!=='—'?'low-score':'empty-score'}">${escapeHtml(r[4])}</td><td><select class="score-input" data-index="${index}" data-slot="5" aria-label="Nota de recuperação semestral para ${escapeHtml(r[0])} — ${escapeHtml(r[2])}">${recoveryScoreOptions(r[5]==='—'?'':r[5])}</select></td><td><select class="replacement-select" data-index="${index}" aria-label="Bimestre substituído para ${escapeHtml(r[0])} — ${escapeHtml(r[2])}"><option value="">Selecionar</option><option value="1º bimestre" ${r[6]==='1º bimestre'?'selected':''}>1º bimestre</option><option value="2º bimestre" ${r[6]==='2º bimestre'?'selected':''}>2º bimestre</option></select></td><td><span class="status ${r[7]==='Concluído'?'ready':'review'}">${escapeHtml(r[7])}</span></td></tr>`).join('');$('.toolbar-count').textContent=`${rows.length} registros`;$$('.score-input').forEach(input=>input.addEventListener('change',e=>{const row=recoveryData[Number(e.target.dataset.index)];const value=e.target.value.trim();row[5]=value?value.replace('.',','):'—';row[7]=(row[5]!=='—'&&row[6]!=='')?'Concluído':'Pendente';recoveryRows($('#search').value)}));$$('.replacement-select').forEach(select=>select.addEventListener('change',e=>{const row=recoveryData[Number(e.target.dataset.index)];row[6]=e.target.value;row[7]=(row[5]!=='—'&&row[6]!=='')?'Concluído':'Pendente';recoveryRows($('#search').value)}));}
function renderClasses(){$('#class-cards').innerHTML=classData.map(c=>`<article class="class-card"><span class="class-symbol">${escapeHtml(c.name.match(/^\d+/)?.[0]||'—')}</span><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.bim)} bimestre • ${escapeHtml(c.students)} alunos</p><div class="progress"><span style="width:${c.status==='wait'?38:Math.max(0,100-c.recovery*8)}%"></span></div><div class="class-card-footer"><span>${escapeHtml(c.recovery)} em recuperação</span><span>${escapeHtml(c.label)}</span></div></article>`).join('');}
function ataRows(className){return recoveryData.filter(r=>r[1]===className).map(r=>`<span>${escapeHtml(r[0])}</span><span>${escapeHtml(r[2])}</span><span>${escapeHtml(r[3])}</span><span>${escapeHtml(r[4])}</span><span>${escapeHtml(r[5]==='—'?'____':r[5])}</span><span>${escapeHtml(r[6]||'____')}</span>`).join('')}
function renderAta(className){const rows=recoveryData.filter(r=>r[1]===className);const paper=$('.paper');if(!paper||!rows.length)return;const heading=paper.querySelector('.paper-center');if(heading&&schoolName)heading.innerHTML=`<strong>GOVERNO DO ESTADO DE SÃO PAULO</strong><br />SECRETARIA DE ESTADO DA EDUCAÇÃO<br />UNIDADE REGIONAL DE ENSINO – REGIÃO DE ADAMANTINA<br />E.E. “${escapeHtml(schoolName)}”<br />MUNICÍPIO DE SAGRES`;paper.querySelector('p:nth-of-type(2)').innerHTML=`Aos ____ dias do mês de agosto de dois mil e vinte e seis, nesta unidade escolar, realizou-se a Avaliação de Recuperação Semestral dos alunos da turma <strong>${escapeHtml(className)}</strong>.`;paper.querySelector('.paper-table').innerHTML='<span>Aluno</span><span>Disciplina</span><span>Nota do primeiro bimestre</span><span>Nota do segundo bimestre</span><span>Nota da recuperação semestral</span><span>Bimestre substituído</span>'+ataRows(className);toast(`ATA de ${className} atualizada.`)}
function renderMinutes(){const groups=[...new Set(recoveryData.map(r=>r[1]))].filter(Boolean);$('#minutes-list').innerHTML=groups.map((name,i)=>{const count=recoveryData.filter(r=>r[1]===name).length;return `<div class="minute-row ${i===0?'selected':''}"><strong>${escapeHtml(name)}</strong><small>${count} registros • Rascunho para revisão</small><button data-ata-class="${escapeHtml(name)}">Revisar ATA →</button></div>`}).join('');$$('[data-ata-class]').forEach(b=>b.onclick=()=>renderAta(b.dataset.ataClass));if(groups[0])renderAta(groups[0]);}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}-view`).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:'Visão geral',recovery:'Recuperação',classes:'Turmas',minutes:'Atas'};$('#page-title').textContent=titles[view];window.scrollTo({top:0,behavior:'smooth'});}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function normal(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase()}
function cleanSubject(v){return String(v??'').replace(/\s*\([12]B\)\s*$/i,'').replace(/\s+\d{3,6}\s*$/,'').trim()}
function cleanClassName(v){return String(v??'').replace(/\.(xlsx|xls)$/i,'').replace(/[_]+/g,' ').replace(/\s+/g,' ').trim()}
function subjectPeriod(v,fallback){const match=normal(v).match(/\(([12])B\)/);return match?`${match[1]}º`:fallback}
function findTurma(rows,fileName){for(const row of rows){for(let i=0;i<row.length;i++){if(normal(row[i])==='TURMA:'||normal(row[i])==='TURMA'){const value=row.slice(i+1).find(v=>String(v??'').trim());if(value)return cleanClassName(value)}}}const fallback=rows.flat().map(v=>String(v??'').trim()).find(v=>/\d+\s*[º°]?\s*ANO\b/i.test(v));if(fallback)return cleanClassName(fallback);const fromName=String(fileName).replace(/\.(xlsx|xls)$/i,'').match(/\d+\s*[º°]?\s*ANO[^_\-]*/i);return fromName?cleanClassName(fromName[0]):'Turma não identificada'}
function bimester(name,metadata=[]){const file=normal(name).replace(/[_-]+/g,' ');const meta=normal(metadata.flat().join(' '));const second=value=>value.includes('SEGUNDO BIMESTRE')||/(^|\D)2\s*[º°O]?\s*BIM/.test(value);const first=value=>value.includes('PRIMEIRO BIMESTRE')||/(^|\D)1\s*[º°O]?\s*BIM/.test(value);if(second(file))return'2º';if(first(file))return'1º';if(second(meta))return'2º';return'1º'}
function parseNumber(v){const raw=typeof v==='number'?v:String(v??'').replace(',','.').replace(/[^0-9.-]/g,'');if(raw==='')return null;const value=Number(raw);return Number.isFinite(value)&&value>=0&&value<=10?value:null}
function extractWorkbook(file){return file.arrayBuffer().then(buffer=>{if(!window.XLSX)throw new Error('Biblioteca Excel indisponível');const book=XLSX.read(buffer,{type:'array',cellDates:false});const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:''});const headerIndex=rows.findIndex(row=>row.some(v=>normal(v)==='ALUNO'));if(headerIndex<0)throw new Error(`ALUNO não encontrado em ${file.name}`);const header=rows[headerIndex];const second=rows[headerIndex+1]||[];const rawLabels=header.map((v,i)=>String(v||second[i]||''));const labels=rawLabels.map(v=>normal(v));const stop=labels.findIndex((v,i)=>i>1&&['TOTAL','TF','FRE(%)','FT AN','FRE AN(%)'].includes(v));const last=stop>0?stop:labels.length;const metadata=rows.slice(0,headerIndex);const turma=findTurma(metadata,file.name);const period=bimester(file.name,metadata);const records=[];for(const row of rows.slice(headerIndex+1)){const aluno=String(row[0]??'').trim();if(!aluno||normal(aluno)==='ALUNO'||aluno.length<4)continue;for(let i=2;i<last;i++){const rawSubject=rawLabels[i];const subject=cleanSubject(rawSubject);if(['M','F','AC'].includes(normal(subject)))continue;const score=parseNumber(row[i]);if(subject&&score!==null&&score<5)records.push({aluno,turma,disciplina:subject,bimestre:subjectPeriod(rawSubject,period),nota:score});}}return {file:file.name,bimestre:period,turma,records}})}
function showImported(parsed){const imported=parsed.flatMap(x=>x.records);if(!imported.length){toast('Arquivos lidos, mas nenhuma nota abaixo de 5,0 foi encontrada.');return}const combined=new Map();for(const r of imported){r.turma=cleanClassName(r.turma);const key=`${r.aluno}|${r.turma}|${r.disciplina}`;const current=combined.get(key)||{aluno:r.aluno,turma:r.turma,disciplina:r.disciplina,first:'—',second:'—'};if(r.bimestre==='1º')current.first=String(r.nota).replace('.',',');if(r.bimestre==='2º')current.second=String(r.nota).replace('.',',');combined.set(key,current)}recoveryData.splice(0,recoveryData.length,...[...combined.values()].map(r=>{const first=parseNumber(r.first),second=parseNumber(r.second);const replacement=r.first==='—'?'2º bimestre':r.second==='—'?'1º bimestre':first<=second?'1º bimestre':'2º bimestre';return [r.aluno,r.turma,r.disciplina,r.first,r.second,'—',replacement,'Pendente']}));const groups=[...new Set(recoveryData.map(r=>r[1]))];const subjects=[...new Set(recoveryData.map(r=>r[2]))].sort();classData.splice(0,classData.length,...groups.map(name=>({name,bim:'1º + 2º',students:new Set(recoveryData.filter(r=>r[1]===name).map(r=>r[0])).size,recovery:recoveryData.filter(r=>r[1]===name).length,status:'review',label:'Conferir'})));$('#class-filter').innerHTML='<option value="all">Todas as turmas</option>'+groups.map(name=>`<option>${escapeHtml(name)}</option>`).join('');$('#subject-filter').innerHTML='<option value="all">Todas as matérias</option>'+subjects.map(name=>`<option>${escapeHtml(name)}</option>`).join('');tableRows();renderClasses();recoveryRows();persistLocal();$('#upload-modal').classList.remove('open');toast(`${parsed.length} arquivos processados. ${recoveryData.length} pendências encontradas.`)}
function exportRecovery(){if(!window.XLSX){toast('Biblioteca Excel indisponível.');return}const rows=[['Aluno','Turma','Disciplina','Nota do primeiro bimestre','Nota do segundo bimestre','Nota da recuperação semestral','Bimestre substituído','Status'],...recoveryData];const book=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet(rows);XLSX.utils.book_append_sheet(book,sheet,'Recuperação');XLSX.writeFile(book,'lista-recuperacao-2026.xlsx');toast('Excel exportado com sucesso.')}
function printAta(){const paper=$('.paper');if(!paper)return;const printWindow=window.open('','_blank','width=900,height=700');if(!printWindow){toast('Navegador bloqueou janela de impressão.');return}printWindow.document.write(`<html lang="pt-BR"><head><title>ATA de recuperação — 2026</title><style>body{font-family:Times New Roman,serif;color:#24352c;padding:40px;line-height:1.5}.paper-center{text-align:center;font-size:12px}.paper h4{text-align:center;margin:25px 0}.paper-table{display:grid;grid-template-columns:2fr 1.4fr 1fr 1fr 1fr 1fr;border-top:1px solid #999;border-bottom:1px solid #999}.paper-table span{padding:6px;border-bottom:1px solid #ddd;font-size:10px}.signatures{display:flex;justify-content:space-around;text-align:center;margin-top:80px}.signatures small{display:block}</style></head><body><div class="paper">${paper.innerHTML}</div><script>window.onload=()=>window.print()<\/script></body></html>`);printWindow.document.close()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#clear-session').onclick=clearSession;$('#open-upload').onclick=()=>$('#upload-modal').classList.add('open');$('#open-upload-2').onclick=()=>$('#upload-modal').classList.add('open');$('#close-upload').onclick=()=>$('#upload-modal').classList.remove('open');$('#folder-input').onchange=async e=>{if(!e.target.files.length)return;toast('Lendo planilhas…');try{const parsed=await Promise.all([...e.target.files].map(extractWorkbook));showImported(parsed)}catch(error){toast(`Não foi possível ler lote: ${error.message}`);console.error(error)}};$('#search').oninput=e=>recoveryRows(e.target.value);$('#class-filter').onchange=()=>recoveryRows($('#search').value);$('#subject-filter').onchange=()=>recoveryRows($('#search').value);$('#export-recovery').onclick=exportRecovery;$('#generate-minutes').onclick=()=>{renderMinutes();toast('ATAs geradas para revisão.')};$('#print-ata').onclick=printAta;$$('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));
clearTemplateAtaSample();restoreLocal();tableRows();recoveryRows();renderClasses();renderMinutes();renderOverview();

function canonicalizeImportedRecords(parsed){const maps={aluno:new Map(),turma:new Map(),disciplina:new Map()};for(const file of parsed){for(const record of file.records||[]){for(const field of Object.keys(maps)){const key=normal(record[field]);if(maps[field].has(key))record[field]=maps[field].get(key);else maps[field].set(key,record[field])}}}return parsed}
const importedHandler=showImported;
showImported=function(parsed){const importedCount=parsed.reduce((total,file)=>total+(file.records||[]).length,0);if(importedCount>MAX_IMPORTED_RECORDS){toast(`Lote excede o limite de ${MAX_IMPORTED_RECORDS} registros.`);return}importedHandler(canonicalizeImportedRecords(parsed))};
function persistBatch(){persistLocal();if(typeof google==='undefined'||!google.script?.run)return;google.script.run.withFailureHandler(error=>console.error('Falha ao salvar lote:',error)).saveRecoveryBatch(recoveryData,schoolName)}
function validateRecoveryScore(event){if(!event.target.matches('.score-input'))return;const raw=event.target.value.trim().replace(',','.');if(raw===''){event.target.setCustomValidity('');return}const score=Number(raw);if(Number.isInteger(score)&&score>=1&&score<=10){event.target.setCustomValidity('');return}event.preventDefault();event.stopImmediatePropagation();const row=recoveryData[Number(event.target.dataset.index)];event.target.value=row&&row[5]!=='—'?String(row[5]).replace(',','.'):'';event.target.setCustomValidity('Informe uma nota inteira entre 1 e 10.');event.target.reportValidity();toast('Nota inválida. Informe uma nota inteira entre 1 e 10.')}
document.addEventListener('change',validateRecoveryScore,true);
document.addEventListener('change',event=>{if(event.target.id!=='folder-input')return;try{validateUploadSelection([...event.target.files])}catch(error){event.preventDefault();event.stopImmediatePropagation();event.target.value='';toast(error.message)}},true);
document.addEventListener('change',event=>{if(event.target.matches('.score-input,.replacement-select'))persistBatch()});
$('#school-name').addEventListener('input',event=>{schoolName=event.target.value.trim();renderMinutes()});
